# Generated by Django 4.2 on 2024-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=255, verbose_name='Номер дома')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень в сети')),
                ('type_company', models.CharField(choices=[('individual', 'индивидуальный'), ('factory', 'завод'), ('retail', 'розница')], max_length=30, verbose_name='Тип Компании')),
                ('supplier_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя компании поставщика')),
                ('supplier_company_id', models.IntegerField(blank=True, null=True, verbose_name='ID компании поставщика')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
